<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<c:set var="pageTitle" value="Add Customer" />
<%@ include file="../layout/header.jsp" %>
<%@ include file="../layout/sidebar.jsp" %>

<div class="fv-main">
    <div class="fv-card">
        <div class="card-header">Customer Registration <a href="${pageContext.request.contextPath}/customer/list" class="btn btn-sm btn-outline-secondary float-end">Back</a></div>
        <div class="card-body">
            <form method="post" action="${pageContext.request.contextPath}/customer/add" class="fv-form">
                <!-- Customer number is auto-generated by the system per CBS CIF convention -->
                <div class="row mb-3">
                    <div class="col-md-6"><label class="form-label">Customer Type *</label><select name="customerType" class="form-select" required><option value="INDIVIDUAL">Individual</option><option value="CORPORATE">Corporate</option></select></div>
                    <div class="col-md-6"><label class="form-label">Branch *</label><select name="branchId" class="form-select" required><c:forEach var="branch" items="${branches}"><option value="${branch.id}"><c:out value="${branch.branchCode}" /> - <c:out value="${branch.branchName}" /></option></c:forEach></select></div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-6"><label class="form-label">First Name *</label><input type="text" name="firstName" class="form-control" required /></div>
                    <div class="col-md-6"><label class="form-label">Last Name *</label><input type="text" name="lastName" class="form-control" required /></div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-6"><label class="form-label">Date of Birth</label><input type="date" name="dateOfBirth" class="form-control" /></div>
                    <div class="col-md-6"><label class="form-label">PAN Number</label><input type="text" name="panNumber" class="form-control" maxlength="10" pattern="[A-Z]{5}[0-9]{4}[A-Z]{1}" placeholder="ABCDE1234F" /></div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-6"><label class="form-label">Aadhaar Number</label><input type="text" name="aadhaarNumber" class="form-control" maxlength="12" pattern="[0-9]{12}" /></div>
                    <div class="col-md-6"><label class="form-label">Mobile Number *</label><input type="text" name="mobileNumber" class="form-control" required maxlength="15" /></div>
                </div>
                <div class="mb-3"><label class="form-label">Email</label><input type="email" name="email" class="form-control" /></div>
                <div class="mb-3"><label class="form-label">Address</label><textarea name="address" class="form-control" rows="2"></textarea></div>
                <div class="row mb-3">
                    <div class="col-md-4"><label class="form-label">City</label><input type="text" name="city" class="form-control" /></div>
                    <div class="col-md-4"><label class="form-label">State</label><input type="text" name="state" class="form-control" /></div>
                    <div class="col-md-4"><label class="form-label">PIN Code</label><input type="text" name="pinCode" class="form-control" maxlength="6" /></div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-6"><label class="form-label">CIBIL Score</label><input type="number" name="cibilScore" class="form-control" min="300" max="900" /></div>
                </div>
                <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" />
                <button type="submit" class="btn btn-fv-primary mt-2">Add Customer</button>
            </form>
        </div>
    </div>
</div>

<%@ include file="../layout/footer.jsp" %>
