<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<c:set var="pageTitle" value="Add Customer" />
<%@ include file="../layout/header.jsp" %>
<%@ include file="../layout/sidebar.jsp" %>

<div class="fv-main">
    <%-- CBS Tier-1: Breadcrumb per Finacle/Temenos --%>
    <ul class="fv-breadcrumb">
        <li><a href="${pageContext.request.contextPath}/dashboard"><i class="bi bi-speedometer2"></i> Home</a></li>
        <li><a href="${pageContext.request.contextPath}/customer/list">Customers</a></li>
        <li class="active">New CIF Registration</li>
    </ul>

    <c:if test="${not empty error}">
        <div class="fv-alert alert alert-danger"><c:out value="${error}" /></div>
    </c:if>
    <div class="fv-card">
        <div class="card-header"><i class="bi bi-person-plus"></i> Customer Registration <div class="float-end"><a href="${pageContext.request.contextPath}/customer/list" class="btn btn-sm btn-outline-secondary" data-fv-cancel="${pageContext.request.contextPath}/customer/list"><i class="bi bi-arrow-left"></i> Back <span class="fv-kbd">F3</span></a></div></div>
        <div class="card-body">
            <form method="post" action="${pageContext.request.contextPath}/customer/add" class="fv-form">
                <!-- Customer number is auto-generated by the system per CBS CIF convention -->
                <div class="row mb-3">
                    <div class="col-md-4 fv-mandatory-group"><label class="form-label fv-required">Customer Type</label><span class="fv-help-icon" data-fv-help="Per RBI KYC Direction: determines CKYC account type (INDIVIDUAL/NON_INDIVIDUAL) and OVD requirements">?</span><select name="customerType" class="form-select" required tabindex="1"><option value="INDIVIDUAL" ${customer.customerType == 'INDIVIDUAL' ? 'selected' : ''}>Individual</option><option value="JOINT" ${customer.customerType == 'JOINT' ? 'selected' : ''}>Joint</option><option value="HUF" ${customer.customerType == 'HUF' ? 'selected' : ''}>HUF</option><option value="PARTNERSHIP" ${customer.customerType == 'PARTNERSHIP' ? 'selected' : ''}>Partnership</option><option value="COMPANY" ${customer.customerType == 'COMPANY' ? 'selected' : ''}>Company</option><option value="TRUST" ${customer.customerType == 'TRUST' ? 'selected' : ''}>Trust</option><option value="NRI" ${customer.customerType == 'NRI' ? 'selected' : ''}>NRI</option><option value="MINOR" ${customer.customerType == 'MINOR' ? 'selected' : ''}>Minor</option><option value="GOVERNMENT" ${customer.customerType == 'GOVERNMENT' ? 'selected' : ''}>Government</option></select></div>
                    <div class="col-md-4 fv-mandatory-group"><label class="form-label fv-required">Branch</label>
                        <c:choose>
                            <c:when test="${pageContext.request.isUserInRole('ROLE_ADMIN')}">
                                <select name="branchId" class="form-select" required><c:forEach var="branch" items="${branches}"><option value="${branch.id}" ${branch.id == defaultBranchId ? 'selected' : ''}><c:out value="${branch.branchCode}" /> - <c:out value="${branch.branchName}" /></option></c:forEach></select>
                            </c:when>
                            <c:otherwise>
                                <c:forEach var="branch" items="${branches}">
                                    <input type="text" class="form-control" value="${branch.branchCode} - ${branch.branchName}" disabled />
                                    <input type="hidden" name="branchId" value="${branch.id}" />
                                </c:forEach>
                            </c:otherwise>
                        </c:choose>
                    </div>
                    <div class="col-md-2"><label class="form-label">KYC Risk</label><span class="fv-help-icon" data-fv-help="Per RBI KYC Section 16: LOW=10yr re-KYC, MEDIUM=8yr, HIGH=2yr. PEP customers are always HIGH.">?</span><select name="kycRiskCategory" class="form-select" tabindex="3"><option value="MEDIUM" ${customer.kycRiskCategory == 'MEDIUM' ? 'selected' : ''}>Medium</option><option value="LOW" ${customer.kycRiskCategory == 'LOW' ? 'selected' : ''}>Low</option><option value="HIGH" ${customer.kycRiskCategory == 'HIGH' ? 'selected' : ''}>High</option></select></div>
                    <div class="col-md-2"><label class="form-label">PEP</label><span class="fv-help-icon" data-fv-help="Per RBI KYC Direction: Politically Exposed Persons require Enhanced Due Diligence (EDD) and mandatory HIGH risk classification.">?</span><div class="form-check mt-2"><input type="hidden" name="_pep" value="on" /><input type="checkbox" name="pep" value="true" class="form-check-input" id="pepCheck" ${customer.pep ? 'checked' : ''} tabindex="4" /><label class="form-check-label" for="pepCheck">Politically Exposed Person</label></div></div>
                </div>
                <div class="fv-section-header" onclick=""><i class="bi bi-person"></i> Personal Details &amp; Demographics (CKYC) <i class="bi bi-chevron-down fv-chevron"></i></div>
                <div class="fv-section-body">
                <div class="row mb-3">
                    <div class="col-md-3 fv-mandatory-group"><label class="form-label fv-required">First Name</label><input type="text" name="firstName" class="form-control" value="<c:out value='${customer.firstName}'/>" required maxlength="100" tabindex="5" /></div>
                    <div class="col-md-3 fv-mandatory-group"><label class="form-label fv-required">Last Name</label><input type="text" name="lastName" class="form-control" value="<c:out value='${customer.lastName}'/>" required maxlength="100" tabindex="6" /></div>
                    <div class="col-md-2 fv-mandatory-group"><label class="form-label fv-required">Gender</label><span class="fv-help-icon" data-fv-help="Per NALSA 2014 / CERSAI: M=Male, F=Female, T=Transgender. Mandatory for INDIVIDUAL-type CKYC.">?</span><select name="gender" class="form-select" required tabindex="7"><option value="">--</option><option value="M" ${customer.gender == 'M' ? 'selected' : ''}>Male</option><option value="F" ${customer.gender == 'F' ? 'selected' : ''}>Female</option><option value="T" ${customer.gender == 'T' ? 'selected' : ''}>Transgender</option></select></div>
                    <div class="col-md-2 fv-mandatory-group"><label class="form-label fv-required">Date of Birth</label><span class="fv-help-icon" data-fv-help="Per CERSAI CKYC v2.0: mandatory for INDIVIDUAL customers. Used for KYC expiry calculation.">?</span><input type="date" name="dateOfBirth" class="form-control" value="${customer.dateOfBirth}" required tabindex="8" /></div>
                    <div class="col-md-2"><label class="form-label">Marital Status</label><select name="maritalStatus" class="form-select" tabindex="9"><option value="">--</option><option value="SINGLE" ${customer.maritalStatus == 'SINGLE' ? 'selected' : ''}>Single</option><option value="MARRIED" ${customer.maritalStatus == 'MARRIED' ? 'selected' : ''}>Married</option><option value="DIVORCED" ${customer.maritalStatus == 'DIVORCED' ? 'selected' : ''}>Divorced</option><option value="WIDOWED" ${customer.maritalStatus == 'WIDOWED' ? 'selected' : ''}>Widowed</option><option value="SEPARATED" ${customer.maritalStatus == 'SEPARATED' ? 'selected' : ''}>Separated</option></select></div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-4 fv-mandatory-group"><label class="form-label fv-required">Father's Name</label><span class="fv-help-icon" data-fv-help="Per CERSAI CKYC v2.0 Section 4.2: mandatory for INDIVIDUAL-type customers. Required for CERSAI upload.">?</span><input type="text" name="fatherName" class="form-control" value="<c:out value='${customer.fatherName}'/>" required maxlength="200" tabindex="10" /></div>
                    <div class="col-md-4 fv-mandatory-group"><label class="form-label fv-required">Mother's Name</label><span class="fv-help-icon" data-fv-help="Per CERSAI CKYC v2.0 Section 4.2: mandatory for INDIVIDUAL-type customers. Required for CERSAI upload.">?</span><input type="text" name="motherName" class="form-control" value="<c:out value='${customer.motherName}'/>" required maxlength="200" tabindex="11" /></div>
                    <div class="col-md-4"><label class="form-label">Spouse Name</label><input type="text" name="spouseName" class="form-control" value="<c:out value='${customer.spouseName}'/>" maxlength="200" tabindex="12" /></div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-3"><label class="form-label">Nationality</label><select name="nationality" class="form-select"><option value="INDIAN" ${customer.nationality == 'INDIAN' or empty customer.nationality ? 'selected' : ''}>Indian</option><option value="NRI" ${customer.nationality == 'NRI' ? 'selected' : ''}>NRI</option><option value="PIO" ${customer.nationality == 'PIO' ? 'selected' : ''}>PIO</option><option value="OCI" ${customer.nationality == 'OCI' ? 'selected' : ''}>OCI</option><option value="FOREIGN" ${customer.nationality == 'FOREIGN' ? 'selected' : ''}>Foreign</option></select></div>
                    <div class="col-md-3"><label class="form-label">Occupation</label><select name="occupationCode" class="form-select"><option value="">--</option><option value="SALARIED_PRIVATE" ${customer.occupationCode == 'SALARIED_PRIVATE' ? 'selected' : ''}>Salaried (Pvt)</option><option value="SALARIED_GOVT" ${customer.occupationCode == 'SALARIED_GOVT' ? 'selected' : ''}>Salaried (Govt)</option><option value="BUSINESS" ${customer.occupationCode == 'BUSINESS' ? 'selected' : ''}>Business</option><option value="PROFESSIONAL" ${customer.occupationCode == 'PROFESSIONAL' ? 'selected' : ''}>Professional</option><option value="SELF_EMPLOYED" ${customer.occupationCode == 'SELF_EMPLOYED' ? 'selected' : ''}>Self Employed</option><option value="RETIRED" ${customer.occupationCode == 'RETIRED' ? 'selected' : ''}>Retired</option><option value="HOUSEWIFE" ${customer.occupationCode == 'HOUSEWIFE' ? 'selected' : ''}>Housewife</option><option value="STUDENT" ${customer.occupationCode == 'STUDENT' ? 'selected' : ''}>Student</option><option value="AGRICULTURIST" ${customer.occupationCode == 'AGRICULTURIST' ? 'selected' : ''}>Agriculturist</option><option value="OTHER" ${customer.occupationCode == 'OTHER' ? 'selected' : ''}>Other</option></select></div>
                    <div class="col-md-3"><label class="form-label">Annual Income Band</label><select name="annualIncomeBand" class="form-select"><option value="">--</option><option value="BELOW_1L" ${customer.annualIncomeBand == 'BELOW_1L' ? 'selected' : ''}>&lt;1L</option><option value="1L_TO_5L" ${customer.annualIncomeBand == '1L_TO_5L' ? 'selected' : ''}>1-5L</option><option value="5L_TO_10L" ${customer.annualIncomeBand == '5L_TO_10L' ? 'selected' : ''}>5-10L</option><option value="10L_TO_25L" ${customer.annualIncomeBand == '10L_TO_25L' ? 'selected' : ''}>10-25L</option><option value="25L_TO_1CR" ${customer.annualIncomeBand == '25L_TO_1CR' ? 'selected' : ''}>25L-1Cr</option><option value="ABOVE_1CR" ${customer.annualIncomeBand == 'ABOVE_1CR' ? 'selected' : ''}>&gt;1Cr</option></select></div>
                    <div class="col-md-3"><label class="form-label">CIBIL Score</label><input type="number" name="cibilScore" class="form-control" value="${customer.cibilScore}" min="300" max="900" /></div>
                </div>

                </div><%-- end Personal Details section body --%>
                <div class="fv-section-header" onclick=""><i class="bi bi-shield-check"></i> KYC Identity Documents <i class="bi bi-chevron-down fv-chevron"></i></div>
                <div class="fv-section-body">
                <div class="row mb-3">
                    <div class="col-md-3"><label class="form-label">PAN Number</label><span class="fv-help-icon" data-fv-help="Per RBI KYC: IMMUTABLE after CIF creation. Format: AAAAA0000A. Validated via 4th-char type check.">?</span><input type="text" name="panNumber" id="panNumber" class="form-control" data-fv-type="pan" value="<c:out value='${customer.panNumber}'/>" maxlength="10" pattern="[A-Z]{5}[0-9]{4}[A-Z]{1}" title="AAAAA0000A" placeholder="ABCDE1234F" tabindex="13" /><small class="text-muted" id="panHint">Immutable after creation</small></div>
                    <div class="col-md-3"><label class="form-label">Aadhaar Number</label><span class="fv-help-icon" data-fv-help="Per UIDAI: IMMUTABLE after CIF creation. 12 digits with Verhoeff checksum. Server validates check digit.">?</span><input type="text" name="aadhaarNumber" id="aadhaarNumber" class="form-control" data-fv-type="aadhaar" value="<c:out value='${customer.aadhaarNumber}'/>" maxlength="12" pattern="[0-9]{12}" title="12 digits" inputmode="numeric" tabindex="14" /><small class="text-muted" id="aadhaarHint">Immutable after creation</small></div>
                    <div class="col-md-3"><label class="form-label">Photo ID Type</label><select name="photoIdType" id="photoIdType" class="form-select" onchange="syncPhotoId();"><option value="">--</option><option value="PASSPORT">Passport</option><option value="VOTER_ID">Voter ID</option><option value="DRIVING_LICENSE">DL</option><option value="PAN_CARD">PAN Card</option><option value="AADHAAR">Aadhaar</option></select></div>
                    <div class="col-md-3"><label class="form-label">Photo ID Number</label><input type="text" name="photoIdNumber" id="photoIdNumber" class="form-control" maxlength="30" /></div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-3"><label class="form-label">Address Proof Type</label><select name="addressProofType" id="addressProofType" class="form-select" onchange="syncAddressProof();"><option value="">--</option><option value="PASSPORT">Passport</option><option value="VOTER_ID">Voter ID</option><option value="UTILITY_BILL">Utility Bill</option><option value="AADHAAR">Aadhaar</option></select></div>
                    <div class="col-md-3"><label class="form-label">Address Proof No.</label><input type="text" name="addressProofNumber" id="addressProofNumber" class="form-control" maxlength="30" /></div>
                    <div class="col-md-3"><label class="form-label">KYC Mode</label><select name="kycMode" class="form-select"><option value="IN_PERSON">In-Person</option><option value="VIDEO_KYC">Video KYC</option><option value="DIGITAL_KYC">Digital KYC</option><option value="CKYC_DOWNLOAD">CKYC Download</option></select></div>
                    <div class="col-md-3"><label class="form-label">CKYC Number (KIN)</label><input type="text" class="form-control bg-light" maxlength="14" placeholder="Auto-assigned by CERSAI" disabled /><small class="text-muted">System-managed after CERSAI registration</small></div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-3 fv-mandatory-group"><label class="form-label fv-required">Mobile Number</label><span class="fv-help-icon" data-fv-help="10-digit Indian mobile starting with 6-9. Used for OTP-based KYC and transaction alerts.">?</span><input type="text" name="mobileNumber" class="form-control" data-fv-type="mobile" value="<c:out value='${customer.mobileNumber}'/>" required maxlength="10" pattern="[6-9][0-9]{9}" title="10-digit mobile" inputmode="numeric" tabindex="19" /></div>
                    <div class="col-md-3"><label class="form-label">Email</label><input type="email" name="email" class="form-control" data-fv-type="email" value="<c:out value='${customer.email}'/>" maxlength="200" tabindex="20" /></div>
                </div>

                </div><%-- end KYC Identity section body --%>
                <div class="fv-section-header" onclick=""><i class="bi bi-geo-alt"></i> Correspondence Address <i class="bi bi-chevron-down fv-chevron"></i></div>
                <div class="fv-section-body">
                <div class="mb-2"><label class="form-label">Address Line</label><textarea name="address" class="form-control" rows="2" maxlength="500" placeholder="Flat/House No, Street, Locality"><c:out value="${customer.address}"/></textarea></div>
                <div class="row mb-3">
                    <div class="col-md-4"><label class="form-label">City</label><input type="text" name="city" class="form-control" value="<c:out value='${customer.city}'/>" maxlength="100" placeholder="City" /></div>
                    <div class="col-md-4"><label class="form-label">State</label><input type="text" name="state" class="form-control" value="<c:out value='${customer.state}'/>" maxlength="100" placeholder="State" /></div>
                    <div class="col-md-4"><label class="form-label">PIN Code</label><input type="text" name="pinCode" class="form-control" data-fv-type="pincode" value="<c:out value='${customer.pinCode}'/>" maxlength="6" pattern="[0-9]{6}" title="6-digit PIN" inputmode="numeric" placeholder="PIN Code" tabindex="23" /></div>
                </div>

                </div><%-- end Correspondence Address section body --%>
                <div class="fv-section-header" onclick=""><i class="bi bi-geo-alt"></i> Permanent Address (CKYC/CERSAI) <i class="bi bi-chevron-down fv-chevron"></i></div>
                <div class="fv-section-body">
                <div class="row mb-2">
                    <div class="col-md-12"><div class="form-check"><input type="hidden" name="_addressSameAsPermanent" value="on" /><input type="checkbox" name="addressSameAsPermanent" value="true" class="form-check-input" id="addrSameAdd" ${customer.addressSameAsPermanent ? 'checked' : (empty customer.firstName ? 'checked' : '')} onchange="togglePermanentAddrAdd();" /><label class="form-check-label" for="addrSameAdd">Same as correspondence address</label></div></div>
                </div>
                <div id="permanentAddrBlockAdd" style="${customer.addressSameAsPermanent or empty customer.firstName ? 'display:none;' : ''}">
                    <div class="mb-2"><textarea name="permanentAddress" class="form-control" rows="2" maxlength="500" placeholder="Permanent address"><c:out value="${customer.permanentAddress}"/></textarea></div>
                    <div class="row mb-3">
                        <div class="col-md-3"><input type="text" name="permanentCity" class="form-control" value="<c:out value='${customer.permanentCity}'/>" maxlength="100" placeholder="City" /></div>
                        <div class="col-md-3"><input type="text" name="permanentState" class="form-control" value="<c:out value='${customer.permanentState}'/>" maxlength="100" placeholder="State" /></div>
                        <div class="col-md-3"><input type="text" name="permanentPinCode" class="form-control" data-fv-type="pincode" value="<c:out value='${customer.permanentPinCode}'/>" maxlength="6" pattern="[0-9]{6}" title="6-digit PIN" inputmode="numeric" placeholder="PIN Code" /></div>
                        <div class="col-md-3"><select name="permanentCountry" class="form-select"><option value="INDIA" ${customer.permanentCountry == 'INDIA' or empty customer.permanentCountry ? 'selected' : ''}>India</option><option value="OTHER" ${customer.permanentCountry != 'INDIA' and not empty customer.permanentCountry ? 'selected' : ''}>Other</option></select></div>
                    </div>
                </div>

                </div><%-- end Permanent Address section body --%>
                <%-- CBS Corporate / Non-Individual Section per RBI KYC Direction §9.
                     Conditionally rendered via JS when customerType is non-individual
                     (COMPANY, PARTNERSHIP, HUF, TRUST, GOVERNMENT). Individual and
                     derived types (INDIVIDUAL, JOINT, MINOR, NRI) hide this block.
                     Fixes JSP/REST-DTO crosswalk finding F4 -- operators were previously
                     unable to onboard corporate CIFs via JSP even though the Customer
                     entity supported all fields (companyName, cin, gstin, etc.). --%>
                <div id="corporateSectionHeader" class="fv-section-header" style="display:none;" onclick=""><i class="bi bi-building"></i> Corporate / Non-Individual Details (RBI KYC §9) <i class="bi bi-chevron-down fv-chevron"></i></div>
                <div id="corporateSectionBody" class="fv-section-body" style="display:none;">
                <div class="row mb-3">
                    <div class="col-md-6 fv-mandatory-group"><label class="form-label fv-required">Company / Entity Name</label><span class="fv-help-icon" data-fv-help="Per RBI KYC Direction §9: mandatory for COMPANY / PARTNERSHIP / TRUST / HUF / GOVERNMENT customers. Must match CoI / Trust Deed / Partnership Deed.">?</span><input type="text" name="companyName" class="form-control" value="<c:out value='${customer.companyName}'/>" maxlength="300" /></div>
                    <div class="col-md-6"><label class="form-label">Constitution Type</label><span class="fv-help-icon" data-fv-help="Per RBI: legal constitution of the entity. Drives CKYC NON_INDIVIDUAL sub-type and disclosure requirements.">?</span><select name="constitutionType" class="form-select">
                        <option value="">-- Select --</option>
                        <option value="PROPRIETORSHIP" ${customer.constitutionType == 'PROPRIETORSHIP' ? 'selected' : ''}>Proprietorship</option>
                        <option value="PARTNERSHIP" ${customer.constitutionType == 'PARTNERSHIP' ? 'selected' : ''}>Partnership</option>
                        <option value="LLP" ${customer.constitutionType == 'LLP' ? 'selected' : ''}>LLP</option>
                        <option value="PRIVATE_LIMITED" ${customer.constitutionType == 'PRIVATE_LIMITED' ? 'selected' : ''}>Private Limited</option>
                        <option value="PUBLIC_LIMITED" ${customer.constitutionType == 'PUBLIC_LIMITED' ? 'selected' : ''}>Public Limited</option>
                        <option value="TRUST" ${customer.constitutionType == 'TRUST' ? 'selected' : ''}>Trust</option>
                        <option value="SOCIETY" ${customer.constitutionType == 'SOCIETY' ? 'selected' : ''}>Society</option>
                        <option value="HUF" ${customer.constitutionType == 'HUF' ? 'selected' : ''}>HUF</option>
                        <option value="COOPERATIVE" ${customer.constitutionType == 'COOPERATIVE' ? 'selected' : ''}>Cooperative</option>
                        <option value="GOVERNMENT" ${customer.constitutionType == 'GOVERNMENT' ? 'selected' : ''}>Government</option>
                    </select></div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-4"><label class="form-label">CIN / LLPIN</label><span class="fv-help-icon" data-fv-help="Corporate Identification Number (MCA, 21 chars) or LLP Identification Number. Mandatory for PRIVATE_LIMITED / PUBLIC_LIMITED / LLP.">?</span><input type="text" name="cin" class="form-control" value="<c:out value='${customer.cin}'/>" maxlength="21" placeholder="L12345MH2000PLC123456" /></div>
                    <div class="col-md-4"><label class="form-label">GSTIN</label><span class="fv-help-icon" data-fv-help="GST Registration Number (15 chars). Required for GST-registered business customers; optional for others.">?</span><input type="text" name="gstin" class="form-control" value="<c:out value='${customer.gstin}'/>" maxlength="15" placeholder="27AAAPL1234C1Z5" /></div>
                    <div class="col-md-4"><label class="form-label">Date of Incorporation</label><input type="date" name="dateOfIncorporation" class="form-control" value="${customer.dateOfIncorporation}" /></div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-12"><label class="form-label">Nature of Business</label><span class="fv-help-icon" data-fv-help="Per CERSAI CKYC v2.0: mandatory for NON_INDIVIDUAL customers. Describe primary business activity (e.g., 'Retail trading of electronic goods').">?</span><textarea name="natureOfBusiness" class="form-control" rows="2" maxlength="200" placeholder="Primary business activity"><c:out value="${customer.natureOfBusiness}"/></textarea></div>
                </div>
                </div><%-- end Corporate section body --%>
                <div class="fv-section-header" onclick=""><i class="bi bi-currency-rupee"></i> Income &amp; Exposure (RBI Norms) <i class="bi bi-chevron-down fv-chevron"></i></div>
                <div class="fv-section-body">
                <div class="row mb-3">
                    <div class="col-md-3"><label class="form-label">Monthly Income (INR)</label><input type="number" name="monthlyIncome" class="form-control" data-fv-type="amount" value="${customer.monthlyIncome}" step="0.01" min="0" tabindex="30" /></div>
                    <div class="col-md-3"><label class="form-label">Max Borrowing Limit (INR)</label><input type="number" name="maxBorrowingLimit" class="form-control" data-fv-type="amount" value="${customer.maxBorrowingLimit}" step="0.01" min="0" tabindex="31" /></div>
                    <div class="col-md-3"><label class="form-label">Employment Type</label><select name="employmentType" class="form-select"><option value="">-- Select --</option><option value="SALARIED" ${customer.employmentType == 'SALARIED' ? 'selected' : ''}>Salaried</option><option value="SELF_EMPLOYED" ${customer.employmentType == 'SELF_EMPLOYED' ? 'selected' : ''}>Self Employed</option><option value="BUSINESS" ${customer.employmentType == 'BUSINESS' ? 'selected' : ''}>Business</option><option value="RETIRED" ${customer.employmentType == 'RETIRED' ? 'selected' : ''}>Retired</option><option value="OTHER" ${customer.employmentType == 'OTHER' ? 'selected' : ''}>Other</option></select></div>
                    <div class="col-md-3"><label class="form-label">Employer Name</label><input type="text" name="employerName" class="form-control" value="<c:out value='${customer.employerName}'/>" /></div>
                </div>

                </div><%-- end Income section body --%>
                <div class="fv-section-header" onclick=""><i class="bi bi-people"></i> Nominee Details (RBI Nomination Guidelines) <i class="bi bi-chevron-down fv-chevron"></i></div>
                <div class="fv-section-body">
                <div class="row mb-3">
                    <div class="col-md-4"><label class="form-label">Nominee Date of Birth</label><input type="date" name="nomineeDob" class="form-control" value="${customer.nomineeDob}" /></div>
                    <div class="col-md-4"><label class="form-label">Nominee Guardian Name</label><input type="text" name="nomineeGuardianName" class="form-control" value="<c:out value='${customer.nomineeGuardianName}'/>" maxlength="200" /><small class="text-muted">Required if nominee is a minor</small></div>
                    <div class="col-md-4"><label class="form-label">Nominee Address</label><input type="text" name="nomineeAddress" class="form-control" value="<c:out value='${customer.nomineeAddress}'/>" maxlength="500" /></div>
                </div>
                </div><%-- end Nominee section body --%>
                <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" />
                <button type="submit" class="btn btn-fv-primary mt-2" data-confirm="Submit CIF registration? The customer record will be created and KYC verification will be required."><i class="bi bi-person-plus"></i> Submit CIF Registration <span class="fv-kbd">F2</span></button>
                <a href="${pageContext.request.contextPath}/customer/list" class="btn btn-outline-secondary mt-2 ms-2" data-fv-cancel="${pageContext.request.contextPath}/customer/list"><i class="bi bi-x-circle"></i> Cancel <span class="fv-kbd">F3</span></a>
            </form>
        </div>
    </div>
</div>

<script>
/* CBS Customer Form — Cross-field linkage per Finacle CIF_MASTER.
   PAN/Aadhaar format validation is now handled by finvanta-validation.js via data-fv-type.
   These functions handle page-specific cross-field auto-population only. */

/* Photo ID Type → auto-populate Photo ID Number from PAN/Aadhaar */
function syncPhotoId() {
    var type = document.getElementById('photoIdType').value;
    var numField = document.getElementById('photoIdNumber');
    if (type === 'PAN_CARD') {
        numField.value = document.getElementById('panNumber').value;
        numField.readOnly = true;
        numField.classList.add('bg-light');
    } else if (type === 'AADHAAR') {
        numField.value = document.getElementById('aadhaarNumber').value;
        numField.readOnly = true;
        numField.classList.add('bg-light');
    } else {
        numField.readOnly = false;
        numField.classList.remove('bg-light');
    }
}

/* Address Proof Type → auto-populate Address Proof Number from Aadhaar */
function syncAddressProof() {
    var type = document.getElementById('addressProofType').value;
    var numField = document.getElementById('addressProofNumber');
    if (type === 'AADHAAR') {
        numField.value = document.getElementById('aadhaarNumber').value;
        numField.readOnly = true;
        numField.classList.add('bg-light');
    } else {
        numField.readOnly = false;
        numField.classList.remove('bg-light');
    }
}

/* Permanent Address toggle */
function togglePermanentAddrAdd() {
    var block = document.getElementById('permanentAddrBlockAdd');
    var checked = document.getElementById('addrSameAdd').checked;
    block.style.display = checked ? 'none' : '';
}

/* CBS Corporate section toggle per RBI KYC §9.
   Non-individual customer types require entity-level KYC fields
   (companyName / CIN / GSTIN / constitution / nature of business).
   INDIVIDUAL / JOINT / MINOR / NRI map to CERSAI INDIVIDUAL sub-type
   and hide the section; the rest are CERSAI NON_INDIVIDUAL. */
var NON_INDIVIDUAL_TYPES = ['HUF', 'PARTNERSHIP', 'COMPANY', 'TRUST', 'GOVERNMENT'];
function toggleCorporateSection() {
    var type = document.querySelector('select[name="customerType"]').value;
    var show = NON_INDIVIDUAL_TYPES.indexOf(type) !== -1;
    document.getElementById('corporateSectionHeader').style.display = show ? '' : 'none';
    document.getElementById('corporateSectionBody').style.display = show ? '' : 'none';
}
document.querySelector('select[name="customerType"]').addEventListener('change', toggleCorporateSection);
/* Run on page load so edit-form rehydration and error re-renders
   (when the form redisplays with operator-entered data) show the
   corporate section if customerType was already non-individual. */
toggleCorporateSection();
</script>

<%@ include file="../layout/footer.jsp" %>
