<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<c:set var="pageTitle" value="Add Customer" />
<%@ include file="../layout/header.jsp" %>
<%@ include file="../layout/sidebar.jsp" %>

<div class="fv-main">
    <c:if test="${not empty error}">
        <div class="fv-alert alert alert-danger"><c:out value="${error}" /></div>
    </c:if>
    <div class="fv-card">
        <div class="card-header"><i class="bi bi-person-plus"></i> Customer Registration <a href="${pageContext.request.contextPath}/customer/list" class="btn btn-sm btn-outline-secondary float-end"><i class="bi bi-arrow-left"></i> Back</a></div>
        <div class="card-body">
            <form method="post" action="${pageContext.request.contextPath}/customer/add" class="fv-form">
                <!-- Customer number is auto-generated by the system per CBS CIF convention -->
                <div class="row mb-3">
                    <div class="col-md-4"><label class="form-label">Customer Type *</label><select name="customerType" class="form-select" required><option value="INDIVIDUAL">Individual</option><option value="JOINT">Joint</option><option value="HUF">HUF</option><option value="PARTNERSHIP">Partnership</option><option value="COMPANY">Company</option><option value="TRUST">Trust</option><option value="NRI">NRI</option><option value="MINOR">Minor</option><option value="GOVERNMENT">Government</option></select></div>
                    <div class="col-md-4"><label class="form-label">Branch *</label><select name="branchId" class="form-select" required><c:forEach var="branch" items="${branches}"><option value="${branch.id}"><c:out value="${branch.branchCode}" /> - <c:out value="${branch.branchName}" /></option></c:forEach></select></div>
                    <div class="col-md-2"><label class="form-label">KYC Risk</label><select name="kycRiskCategory" class="form-select"><option value="MEDIUM">Medium</option><option value="LOW">Low</option><option value="HIGH">High</option></select></div>
                    <div class="col-md-2"><label class="form-label">PEP</label><div class="form-check mt-2"><input type="checkbox" name="pep" value="true" class="form-check-input" id="pepCheck" /><label class="form-check-label" for="pepCheck">Politically Exposed Person</label></div></div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-6"><label class="form-label">First Name *</label><input type="text" name="firstName" class="form-control" required /></div>
                    <div class="col-md-6"><label class="form-label">Last Name *</label><input type="text" name="lastName" class="form-control" required /></div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-6"><label class="form-label">Date of Birth</label><input type="date" name="dateOfBirth" class="form-control" /></div>
                    <div class="col-md-6"><label class="form-label">PAN Number</label><input type="text" name="panNumber" class="form-control" maxlength="10" pattern="[A-Z]{5}[0-9]{4}[A-Z]{1}" title="PAN format: AAAAA0000A" placeholder="ABCDE1234F" style="text-transform:uppercase;" oninput="this.value=this.value.toUpperCase();" /><small class="text-muted">Immutable after creation</small></div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-6"><label class="form-label">Aadhaar Number</label><input type="text" name="aadhaarNumber" class="form-control" maxlength="12" pattern="[0-9]{12}" title="Aadhaar: exactly 12 digits" placeholder="123456789012" inputmode="numeric" onkeypress="return event.charCode>=48&&event.charCode<=57" /><small class="text-muted">Immutable after creation</small></div>
                    <div class="col-md-6"><label class="form-label">Mobile Number *</label><input type="text" name="mobileNumber" class="form-control" required maxlength="10" pattern="[6-9][0-9]{9}" title="10-digit mobile starting with 6-9" placeholder="9876543210" inputmode="numeric" onkeypress="return event.charCode>=48&&event.charCode<=57" /></div>
                </div>
                <div class="mb-3"><label class="form-label">Email</label><input type="email" name="email" class="form-control" /></div>
                <div class="mb-3"><label class="form-label">Address</label><textarea name="address" class="form-control" rows="2"></textarea></div>
                <div class="row mb-3">
                    <div class="col-md-4"><label class="form-label">City</label><input type="text" name="city" class="form-control" /></div>
                    <div class="col-md-4"><label class="form-label">State</label><input type="text" name="state" class="form-control" /></div>
                    <div class="col-md-4"><label class="form-label">PIN Code</label><input type="text" name="pinCode" class="form-control" maxlength="6" /></div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-6"><label class="form-label">CIBIL Score</label><input type="number" name="cibilScore" class="form-control" min="300" max="900" /></div>
                </div>
                <hr />
                <h6 class="mb-3">Income &amp; Exposure (RBI Exposure Norms)</h6>
                <div class="row mb-3">
                    <div class="col-md-3"><label class="form-label">Monthly Income (INR)</label><input type="number" name="monthlyIncome" class="form-control" step="0.01" min="0" /></div>
                    <div class="col-md-3"><label class="form-label">Max Borrowing Limit (INR)</label><input type="number" name="maxBorrowingLimit" class="form-control" step="0.01" min="0" /></div>
                    <div class="col-md-3"><label class="form-label">Employment Type</label><select name="employmentType" class="form-select"><option value="">-- Select --</option><option value="SALARIED">Salaried</option><option value="SELF_EMPLOYED">Self Employed</option><option value="BUSINESS">Business</option><option value="RETIRED">Retired</option><option value="OTHER">Other</option></select></div>
                    <div class="col-md-3"><label class="form-label">Employer Name</label><input type="text" name="employerName" class="form-control" /></div>
                </div>
                <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}" />
                <button type="submit" class="btn btn-sm btn-fv-primary mt-2"><i class="bi bi-plus-circle"></i> Add Customer</button>
            </form>
        </div>
    </div>
</div>

<%@ include file="../layout/footer.jsp" %>
