package com.finvanta.config;

import com.finvanta.domain.entity.AppUser;
import com.finvanta.domain.enums.UserRole;
import com.finvanta.repository.AppUserRepository;
import com.finvanta.util.TenantContext;

import java.security.SecureRandom;
import java.time.LocalDate;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.core.annotation.Order;
import org.springframework.core.env.Environment;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

/**
 * CBS Production Bootstrap Initializer per Finacle Day Zero / Temenos Installation.
 *
 * Per Tier-1 CBS standards (Finacle/Temenos/BNP):
 * In production, seed data (data.sql) is NEVER loaded. The database starts empty
 * after DDL migration. The first ADMIN user must be created through a secure
 * bootstrap process — not via SQL scripts with plaintext passwords.
 *
 * This initializer runs ONCE on first startup when no users exist:
 * 1. Checks if any users exist in the database
 * 2. If empty → creates the initial SYSTEM_ADMIN user
 * 3. Password is either from environment variable or auto-generated
 * 4. Password is bcrypt-hashed (never plaintext in production)
 * 5. Password expiry is set to today (forces change on first login)
 * 6. Credentials are logged to console ONCE (never to file per RBI)
 *
 * Per RBI IT Governance Direction 2023 Section 8.2:
 * - Initial credentials must be changed on first login
 * - Default/well-known passwords must never be deployed
 * - Bootstrap credentials must not persist in logs or config files
 *
 * Environment variables:
 *   CBS_ADMIN_USERNAME  — Initial admin username (default: sysadmin)
 *   CBS_ADMIN_PASSWORD  — Initial admin password (auto-generated if not set)
 *   CBS_ADMIN_EMAIL     — Initial admin email (default: admin@localhost)
 *   CBS_ADMIN_TENANT    — Tenant code (default: DEFAULT)
 *
 * Per Finacle: the SYSTEM user is created by DBA during installation.
 * Per Temenos: SYSTEM.ADMIN is pre-configured with a one-time password.
 * This initializer provides the equivalent for Spring Boot deployments.
 */
@Component
@Order(100) // Run after all other initializers (Hibernate DDL, data.sql, etc.)
public class CbsBootstrapInitializer implements ApplicationRunner {

    private static final Logger log = LoggerFactory.getLogger(CbsBootstrapInitializer.class);

    /** Characters for auto-generated password: uppercase + lowercase + digits + special */
    private static final String PASSWORD_CHARS =
            "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789@#$%&*!";
    private static final int AUTO_PASSWORD_LENGTH = 16;

    private final AppUserRepository userRepository;
    private final PasswordEncoder passwordEncoder;
    private final Environment environment;

    public CbsBootstrapInitializer(
            AppUserRepository userRepository,
            PasswordEncoder passwordEncoder,
            Environment environment) {
        this.userRepository = userRepository;
        this.passwordEncoder = passwordEncoder;
        this.environment = environment;
    }

    @Override
    public void run(ApplicationArguments args) {
        String tenantId = environment.getProperty("CBS_ADMIN_TENANT", "DEFAULT");

        // Set tenant context for the bootstrap operation
        TenantContext.setCurrentTenant(tenantId);
        try {
            // Check if any users exist — bootstrap only on truly empty database
            long userCount = userRepository.count();
            if (userCount > 0) {
                log.debug("CBS Bootstrap: {} users exist — skipping initial admin creation.", userCount);
                return;
            }

            // No users exist — create the initial ADMIN
            String username = environment.getProperty("CBS_ADMIN_USERNAME", "sysadmin");
            String email = environment.getProperty("CBS_ADMIN_EMAIL", "admin@localhost");
            String rawPassword = environment.getProperty("CBS_ADMIN_PASSWORD");

            boolean autoGenerated = false;
            if (rawPassword == null || rawPassword.isBlank()) {
                rawPassword = generateSecurePassword();
                autoGenerated = true;
            }

            AppUser admin = new AppUser();
            admin.setTenantId(tenantId);
            admin.setUsername(username);
            admin.setPasswordHash(passwordEncoder.encode(rawPassword));
            admin.setFullName("System Administrator (Bootstrap)");
            admin.setEmail(email);
            admin.setRole(UserRole.ADMIN);
            admin.setActive(true);
            admin.setLocked(false);
            admin.setFailedLoginAttempts(0);
            admin.setMfaEnabled(false);
            // CBS: Force password change on first login per RBI IT Governance §8.2.
            // Setting passwordExpiryDate to today ensures MfaAuthenticationSuccessHandler
            // detects isPasswordExpired()=true and redirects to /password/change.
            admin.setPasswordExpiryDate(LocalDate.now());
            admin.setCreatedBy("SYSTEM_BOOTSTRAP");
            admin.setUpdatedBy("SYSTEM_BOOTSTRAP");
            userRepository.save(admin);

            // CBS CRITICAL: Log credentials to CONSOLE ONLY — never to file appenders.
            // Per RBI IT Governance Direction 2023: bootstrap credentials must not persist
            // in log files. The System.out.println bypasses SLF4J/logback file routing.
            // The admin must note these credentials and change the password immediately.
            System.out.println();
            System.out.println("╔══════════════════════════════════════════════════════════════╗");
            System.out.println("║  CBS BOOTSTRAP: Initial Admin User Created                  ║");
            System.out.println("╠══════════════════════════════════════════════════════════════╣");
            System.out.println("║  Username : " + padRight(username, 48) + "║");
            if (autoGenerated) {
                System.out.println("║  Password : " + padRight(rawPassword, 48) + "║");
            } else {
                System.out.println("║  Password : (from CBS_ADMIN_PASSWORD env var)                ║");
            }
            System.out.println("║  Tenant   : " + padRight(tenantId, 48) + "║");
            System.out.println("║  Role     : ADMIN                                           ║");
            System.out.println("╠══════════════════════════════════════════════════════════════╣");
            System.out.println("║  ⚠ PASSWORD CHANGE REQUIRED ON FIRST LOGIN                  ║");
            System.out.println("║  ⚠ NOTE: Branch must be assigned via DB before login         ║");
            System.out.println("╚══════════════════════════════════════════════════════════════╝");
            System.out.println();

            log.info("CBS Bootstrap: Initial ADMIN user '{}' created for tenant '{}'. "
                    + "Password change required on first login.", username, tenantId);

        } finally {
            TenantContext.clear();
        }
    }

    /**
     * Generates a cryptographically secure random password.
     * Per RBI IT Governance: auto-generated passwords must meet complexity requirements
     * (uppercase + lowercase + digit + special, minimum 12 characters).
     */
    private String generateSecurePassword() {
        SecureRandom random = new SecureRandom();
        StringBuilder password = new StringBuilder(AUTO_PASSWORD_LENGTH);
        for (int i = 0; i < AUTO_PASSWORD_LENGTH; i++) {
            password.append(PASSWORD_CHARS.charAt(random.nextInt(PASSWORD_CHARS.length())));
        }
        return password.toString();
    }

    private static String padRight(String text, int length) {
        if (text.length() >= length) return text.substring(0, length);
        return text + " ".repeat(length - text.length());
    }
}