package com.finvanta.config;

import com.finvanta.domain.entity.AppUser;
import com.finvanta.domain.entity.Branch;
import com.finvanta.domain.entity.GLMaster;
import com.finvanta.domain.entity.Tenant;
import com.finvanta.domain.enums.BranchType;
import com.finvanta.domain.enums.GLAccountType;
import com.finvanta.domain.enums.UserRole;
import com.finvanta.repository.AppUserRepository;
import com.finvanta.repository.BranchRepository;
import com.finvanta.repository.GLMasterRepository;
import com.finvanta.repository.TenantRepository;
import com.finvanta.service.BusinessDateService;
import com.finvanta.util.TenantContext;

import java.math.BigDecimal;
import java.security.SecureRandom;
import java.time.LocalDate;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.core.annotation.Order;
import org.springframework.core.env.Environment;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

/**
 * CBS Day Zero Installation Pipeline per Finacle INSTALL_BANK / Temenos INSTALL.COMPANY.
 *
 * Per Tier-1 CBS standards: the installation program creates a FULLY OPERATIONAL
 * system in a single atomic pipeline. After bootstrap, the admin logs in and can
 * transact immediately — no manual DBA SQL scripts required.
 *
 * Pipeline (runs ONCE when app_users table is empty):
 *   Step 1: Tenant       — bank identity per RBI Banking Regulation Act 1949
 *   Step 2: Head Office  — consolidation point per Finacle SOL hierarchy
 *   Step 3: Op. Branch   — first operational branch for transactions per RBI §23
 *   Step 4: GL Chart     — 27 Indian Banking Standard GL codes (1xxx–5xxx)
 *   Step 5: ADMIN user   — with branch assigned, password expired (T-1)
 *   Step 6: Calendar     — current month generated for all operational branches
 *   Step 7: Day Open     — first business day opened, txn batches auto-created
 *
 * Per RBI IT Governance Direction 2023 §8.2:
 * - Credentials printed to console stdout ONLY (never to log files)
 * - Password expired immediately — forces change on first login
 *
 * Environment variables:
 *   CBS_ADMIN_TENANT    — Tenant code (default: DEFAULT)
 *   CBS_ADMIN_USERNAME  — Admin username (default: sysadmin)
 *   CBS_ADMIN_PASSWORD  — Admin password (default: auto-generated)
 *   CBS_ADMIN_EMAIL     — Admin email (default: admin@localhost)
 */
@Component
@Order(100)
public class CbsBootstrapInitializer implements ApplicationRunner {

    private static final Logger log = LoggerFactory.getLogger(CbsBootstrapInitializer.class);

    private static final String PASSWORD_CHARS =
            "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789@#$%&*!";
    private static final int AUTO_PASSWORD_LENGTH = 16;
    private static final String BOOTSTRAP_USER = "SYSTEM_BOOTSTRAP";

    private final AppUserRepository userRepository;
    private final TenantRepository tenantRepository;
    private final BranchRepository branchRepository;
    private final GLMasterRepository glMasterRepository;
    private final BusinessDateService businessDateService;
    private final PasswordEncoder passwordEncoder;
    private final Environment environment;

    public CbsBootstrapInitializer(
            AppUserRepository userRepository,
            TenantRepository tenantRepository,
            BranchRepository branchRepository,
            GLMasterRepository glMasterRepository,
            BusinessDateService businessDateService,
            PasswordEncoder passwordEncoder,
            Environment environment) {
        this.userRepository = userRepository;
        this.tenantRepository = tenantRepository;
        this.branchRepository = branchRepository;
        this.glMasterRepository = glMasterRepository;
        this.businessDateService = businessDateService;
        this.passwordEncoder = passwordEncoder;
        this.environment = environment;
    }

    @Override
    public void run(ApplicationArguments args) {
        String tenantId = environment.getProperty("CBS_ADMIN_TENANT", "DEFAULT");

        // Set tenant context for the bootstrap operation
        TenantContext.setCurrentTenant(tenantId);
        try {
            // Check if any users exist — bootstrap only on truly empty database
            long userCount = userRepository.count();
            if (userCount > 0) {
                log.debug("CBS Bootstrap: {} users exist — skipping initial admin creation.", userCount);
                return;
            }

            // No users exist — create the initial ADMIN
            String username = environment.getProperty("CBS_ADMIN_USERNAME", "sysadmin");
            String email = environment.getProperty("CBS_ADMIN_EMAIL", "admin@localhost");
            String rawPassword = environment.getProperty("CBS_ADMIN_PASSWORD");

            boolean autoGenerated = false;
            if (rawPassword == null || rawPassword.isBlank()) {
                rawPassword = generateSecurePassword();
                autoGenerated = true;
            }

            AppUser admin = new AppUser();
            admin.setTenantId(tenantId);
            admin.setUsername(username);
            admin.setPasswordHash(passwordEncoder.encode(rawPassword));
            admin.setFullName("System Administrator (Bootstrap)");
            admin.setEmail(email);
            admin.setRole(UserRole.ADMIN);
            admin.setActive(true);
            admin.setLocked(false);
            admin.setFailedLoginAttempts(0);
            admin.setMfaEnabled(false);
            // CBS: Force password change on first login per RBI IT Governance §8.2.
            // AppUser.isPasswordExpired() uses LocalDate.now().isAfter(passwordExpiryDate).
            // Setting expiry to TODAY would return false (isAfter is exclusive — same day
            // is NOT "after"). The admin could access the full CBS dashboard on bootstrap
            // day without changing the password. Per Finacle Day Zero / Temenos SYSTEM.ADMIN:
            // initial credentials expire IMMEDIATELY. Setting to yesterday (T-1) guarantees
            // isPasswordExpired()=true on the very first login attempt.
            admin.setPasswordExpiryDate(LocalDate.now().minusDays(1));
            admin.setCreatedBy("SYSTEM_BOOTSTRAP");
            admin.setUpdatedBy("SYSTEM_BOOTSTRAP");
            userRepository.save(admin);

            // CBS CRITICAL: Log credentials to CONSOLE ONLY — never to file appenders.
            // Per RBI IT Governance Direction 2023: bootstrap credentials must not persist
            // in log files. The System.out.println bypasses SLF4J/logback file routing.
            // The admin must note these credentials and change the password immediately.
            System.out.println();
            System.out.println("╔══════════════════════════════════════════════════════════════╗");
            System.out.println("║  CBS BOOTSTRAP: Initial Admin User Created                  ║");
            System.out.println("╠══════════════════════════════════════════════════════════════╣");
            System.out.println("║  Username : " + padRight(username, 48) + "║");
            if (autoGenerated) {
                System.out.println("║  Password : " + padRight(rawPassword, 48) + "║");
            } else {
                System.out.println("║  Password : (from CBS_ADMIN_PASSWORD env var)                ║");
            }
            System.out.println("║  Tenant   : " + padRight(tenantId, 48) + "║");
            System.out.println("║  Role     : ADMIN                                           ║");
            System.out.println("╠══════════════════════════════════════════════════════════════╣");
            System.out.println("║  ⚠ PASSWORD CHANGE REQUIRED ON FIRST LOGIN                  ║");
            System.out.println("║  ⚠ NOTE: Branch must be assigned via DB before login         ║");
            System.out.println("╚══════════════════════════════════════════════════════════════╝");
            System.out.println();

            log.info("CBS Bootstrap: Initial ADMIN user '{}' created for tenant '{}'. "
                    + "Password change required on first login.", username, tenantId);

        } finally {
            TenantContext.clear();
        }
    }

    /**
     * Generates a cryptographically secure random password.
     * Per RBI IT Governance: auto-generated passwords must meet complexity requirements
     * (uppercase + lowercase + digit + special, minimum 12 characters).
     */
    private String generateSecurePassword() {
        SecureRandom random = new SecureRandom();
        StringBuilder password = new StringBuilder(AUTO_PASSWORD_LENGTH);
        for (int i = 0; i < AUTO_PASSWORD_LENGTH; i++) {
            password.append(PASSWORD_CHARS.charAt(random.nextInt(PASSWORD_CHARS.length())));
        }
        return password.toString();
    }

    private static String padRight(String text, int length) {
        if (text.length() >= length) return text.substring(0, length);
        return text + " ".repeat(length - text.length());
    }
}