package com.finvanta.domain.entity;

import com.finvanta.domain.enums.TransactionType;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Table(name = "loan_transactions",
    indexes = {
        @Index(name = "idx_loantxn_tenant_account", columnList = "tenant_id, loan_account_id"),
        @Index(name = "idx_loantxn_txnref", columnList = "tenant_id, transaction_ref", unique = true),
        @Index(name = "idx_loantxn_value_date", columnList = "tenant_id, value_date"),
        @Index(name = "idx_loantxn_type", columnList = "tenant_id, transaction_type"),
        @Index(name = "idx_loantxn_voucher", columnList = "tenant_id, voucher_number")
    }
    // CBS Idempotency: unique constraint on (tenant_id, idempotency_key) for non-null keys.
    // NOT enforced via JPA @UniqueConstraint because H2 (used in tests) treats NULL as a
    // value in unique indexes — two system-generated transactions with idempotency_key=NULL
    // would collide. The SQL standard says NULL != NULL, but H2 does not follow this.
    //
    // Production enforcement:
    //   SQL Server: filtered unique index in DDL (WHERE idempotency_key IS NOT NULL)
    //   Application: LoanAccountServiceImpl.processRepayment() checks before insert
)
@Getter
@Setter
@NoArgsConstructor
public class LoanTransaction extends BaseEntity {

    @Column(name = "transaction_ref", nullable = false, length = 40)
    private String transactionRef;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "loan_account_id", nullable = false)
    private LoanAccount loanAccount;

    @Enumerated(EnumType.STRING)
    @Column(name = "transaction_type", nullable = false, length = 30)
    private TransactionType transactionType;

    @Column(name = "amount", nullable = false, precision = 18, scale = 2)
    private BigDecimal amount;

    @Column(name = "principal_component", precision = 18, scale = 2)
    private BigDecimal principalComponent = BigDecimal.ZERO;

    @Column(name = "interest_component", precision = 18, scale = 2)
    private BigDecimal interestComponent = BigDecimal.ZERO;

    @Column(name = "penalty_component", precision = 18, scale = 2)
    private BigDecimal penaltyComponent = BigDecimal.ZERO;

    @Column(name = "value_date", nullable = false)
    private LocalDate valueDate;

    @Column(name = "posting_date", nullable = false)
    private LocalDateTime postingDate;

    @Column(name = "balance_after", nullable = false, precision = 18, scale = 2)
    private BigDecimal balanceAfter;

    @Column(name = "narration", length = 500)
    private String narration;

    @Column(name = "is_reversed", nullable = false)
    private boolean reversed = false;

    /**
     * CBS Reversal Cross-Reference per Finacle TRAN_REVERSAL / Temenos REVERSAL.TRANSACTION.
     *
     * This field is BIDIRECTIONAL — its meaning depends on the transaction's state:
     *
     * 1. On the ORIGINAL transaction (reversed=true):
     *    → Points to the REVERSAL transaction ref that cancelled this transaction.
     *    → Example: Original TXN001 reversed by TXN002 → TXN001.reversedByRef = "TXN002"
     *
     * 2. On the REVERSAL transaction (reversed=false, transactionType=REVERSAL):
     *    → Points to the ORIGINAL transaction ref that this reversal cancels.
     *    → Example: Reversal TXN002 cancels TXN001 → TXN002.reversedByRef = "TXN001"
     *
     * Disambiguation rule (used by Transaction360Service):
     *    if (txn.isReversed() && reversedByRef != null)  → reversedByRef = reversal ref
     *    if (!txn.isReversed() && reversedByRef != null)  → reversedByRef = original ref
     *
     * Per CBS audit standards: both the original and reversal must be cross-linked
     * for complete audit trail. Neither is ever deleted (immutable financial records).
     */
    @Column(name = "reversed_by_ref", length = 40)
    private String reversedByRef;

    @Column(name = "journal_entry_id")
    private Long journalEntryId;

    /**
     * CBS Voucher Number per Finacle/Temenos TRAN_POSTING convention.
     *
     * Generated by TransactionEngine (Step 9) and persisted here for:
     * - Reconciliation queries (find transaction by voucher number)
     * - Branch-level daily voucher register (RBI audit requirement)
     * - Cross-referencing with physical voucher books
     *
     * Format: VCH/{branchCode}/{YYYYMMDD}/{sequence}
     * Example: "VCH/HQ001/20260401/000042"
     *
     * All transactions (user-initiated and EOD system-generated) route through
     * TransactionEngine, so every LoanTransaction has a voucher number.
     */
    @Column(name = "voucher_number", length = 40)
    private String voucherNumber;

    /**
     * CBS Idempotency Key per Finacle/Temenos UNIQUE.REF pattern.
     *
     * Client-supplied key that uniquely identifies a transaction request.
     * If a retry sends the same idempotency key, the system returns the
     * existing transaction instead of creating a duplicate.
     *
     * Format: caller-defined (typically: channel + accountNo + timestamp + nonce)
     * Example: "WEB-LN001-20240401-abc123"
     *
     * Per CBS standards:
     * - Unique constraint prevents duplicate processing on network retries
     * - Null = no idempotency protection (system-generated transactions like accrual)
     * - Non-null = client-initiated transactions (repayment, prepayment, fee)
     */
    @Column(name = "idempotency_key", length = 100, unique = false)
    private String idempotencyKey;
}
