package com.finvanta.compliance;

import com.finvanta.audit.AuditService;
import com.finvanta.util.BusinessException;
import com.finvanta.util.ReferenceGenerator;
import com.finvanta.util.SecurityUtil;
import com.finvanta.util.TenantContext;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * CBS AML/CFT Compliance Service per Finacle AML_ENGINE / Temenos FC.MONITORING.
 *
 * <p>Central service for Anti-Money Laundering and Counter-Financing of Terrorism
 * compliance per PMLA 2002 and RBI Master Direction on KYC 2016.
 *
 * <p><b>Responsibilities:</b>
 * <ul>
 *   <li><b>CTR Generation:</b> Creates Cash Transaction Report records for
 *       transactions flagged by {@code TransactionValidationService.evaluateRbiComplianceFlags()}.
 *       Called by the outbox event processor when CTR_REPORTABLE events are dispatched.</li>
 *   <li><b>STR Filing:</b> Manages the STR lifecycle (DRAFT → UNDER_REVIEW → APPROVED → FILED).
 *       STRs can be auto-generated by monitoring rules or manually created by compliance officers.</li>
 *   <li><b>Risk Scoring:</b> Evaluates customer risk based on transaction patterns,
 *       geography, product mix, and external data (PEP lists, sanctions).</li>
 * </ul>
 *
 * <p><b>Non-blocking principle per RBI PMLA:</b> AML checks flag but do NOT block
 * transactions. Blocking would tip off the customer (tipping-off is a PMLA offense
 * under Section 66). The transaction completes normally; the compliance team
 * investigates the flagged activity post-facto.
 *
 * <p><b>Integration with TransactionEngine:</b>
 * <pre>
 *   TransactionEngine.executeInternal()
 *     → Step 1.5: TransactionValidationService.evaluateRbiComplianceFlags()
 *       → Sets RBI_FLAG_CTR on cash >= 10L
 *     → Step 11: publishOutboxEvent() with rbiFlags
 *       → Outbox processor calls AmlComplianceService.generateCtrRecord()
 * </pre>
 *
 * @see com.finvanta.transaction.TransactionValidationService
 */
@Service
public class AmlComplianceService {

    private static final Logger log = LoggerFactory.getLogger(AmlComplianceService.class);

    /** RBI PMLA: CTR filing deadline — 15th of the month following the transaction */
    private static final int CTR_FILING_DEADLINE_DAY = 15;

    /** RBI PMLA: STR filing deadline — 7 days from detection */
    private static final int STR_FILING_DEADLINE_DAYS = 7;

    private final AuditService auditService;

    public AmlComplianceService(AuditService auditService) {
        this.auditService = auditService;
    }

    /**
     * Generates a CTR record for a cash transaction that exceeded the ₹10L threshold.
     *
     * <p>Called by the outbox event processor when a CTR_REPORTABLE event is dispatched.
     * The CTR record is stored in PENDING status until the monthly batch filing job
     * collects all PENDING CTRs and submits them to FIU-IND.
     *
     * <p>Per RBI KYC Master Direction Section 28(2): Cash transactions of INR 10 lakh
     * or more (whether in a single transaction or several transactions in a day)
     * must be reported to FIU-IND by the 15th of the following month.
     *
     * @param customerId      Customer ID for the account holder
     * @param accountReference Account number
     * @param transactionRef  Transaction reference from TransactionEngine
     * @param transactionDate Value date of the transaction
     * @param transactionType CASH_DEPOSIT or CASH_WITHDRAWAL
     * @param amount          Transaction amount (>= 10L)
     * @param branchCode      Branch where transaction occurred
     */
    @Transactional
    public void generateCtrRecord(
            Long customerId,
            String accountReference,
            String transactionRef,
            LocalDate transactionDate,
            String transactionType,
            BigDecimal amount,
            String branchCode) {

        String tenantId = TenantContext.getCurrentTenant();
        String ctrReference = "CTR/" + tenantId + "/" + ReferenceGenerator.generateTransactionRef();

        // Determine reporting month (first day of the transaction month)
        LocalDate reportingMonth = transactionDate.withDayOfMonth(1);

        log.info("CTR record generated: ref={}, customer={}, account={}, amount={}, type={}",
                ctrReference, customerId, accountReference, amount, transactionType);

        auditService.logEvent(
                "AML_CTR",
                null,
                "CTR_GENERATED",
                null,
                ctrReference,
                "COMPLIANCE",
                "CTR generated: txnRef=" + transactionRef
                        + ", amount=INR " + amount
                        + ", type=" + transactionType
                        + ", account=" + accountReference);

        // NOTE: Actual DB persistence requires AmlCtrReportRepository.
        // This service method defines the contract and audit trail.
        // Repository wiring will be added when JPA entities for aml_ctr_reports
        // are created in the next implementation chunk.
    }

    /**
     * Creates a Suspicious Transaction Report (STR) in DRAFT status.
     *
     * <p>Per RBI KYC Master Direction Section 29: Banks must report suspicious
     * transactions to FIU-IND within 7 days of detection. The STR goes through
     * a maker-checker workflow: DRAFT → UNDER_REVIEW → APPROVED → FILED.
     *
     * <p>STRs can be created by:
     * <ul>
     *   <li>Automated monitoring rules (detection_method = RULE_ENGINE)</li>
     *   <li>Branch staff manual referral (detection_method = MANUAL_REFERRAL)</li>
     *   <li>Audit findings (detection_method = AUDIT_FINDING)</li>
     * </ul>
     *
     * <p><b>CRITICAL per PMLA Section 66:</b> The existence of an STR must NOT
     * be disclosed to the customer (tipping-off offense). STR records are
     * restricted to ADMIN and COMPLIANCE roles only.
     *
     * @param customerId      Customer under suspicion
     * @param accountReference Account involved (nullable for cross-account patterns)
     * @param category        STR category (STRUCTURING, RAPID_MOVEMENT, etc.)
     * @param amount          Suspicious amount (nullable for pattern-based STRs)
     * @param narrative       Free-text description of suspicious activity
     * @param detectionMethod How the suspicion was detected
     * @param ruleId          Monitoring rule ID (nullable for manual STRs)
     * @param riskScore       Computed risk score
     * @return STR reference number
     */
    @Transactional
    public String createStr(
            Long customerId,
            String accountReference,
            String category,
            BigDecimal amount,
            String narrative,
            String detectionMethod,
            String ruleId,
            int riskScore) {

        String tenantId = TenantContext.getCurrentTenant();
        String currentUser = SecurityUtil.getCurrentUsername();

        if (narrative == null || narrative.isBlank()) {
            throw new BusinessException("STR_NARRATIVE_REQUIRED",
                    "STR narrative is mandatory per FIU-IND filing requirements");
        }

        String strReference = "STR/" + tenantId + "/" + ReferenceGenerator.generateTransactionRef();

        log.info("STR created: ref={}, customer={}, category={}, method={}, score={}",
                strReference, customerId, category, detectionMethod, riskScore);

        auditService.logEvent(
                "AML_STR",
                null,
                "STR_CREATED",
                null,
                strReference,
                "COMPLIANCE",
                "STR created: customer=" + customerId
                        + ", category=" + category
                        + ", amount=" + amount
                        + ", method=" + detectionMethod
                        + ", riskScore=" + riskScore
                        + ", by=" + currentUser);

        return strReference;
    }

    /**
     * Evaluates customer AML risk score based on configurable factors.
     *
     * <p>Per RBI KYC Master Direction Section 16: Risk-based approach to CDD.
     * Risk score is a composite of:
     * <ul>
     *   <li>Customer type (individual=0, trust=+20, shell company=+30)</li>
     *   <li>Geography (domestic=0, high-risk country=+25)</li>
     *   <li>Product mix (savings=0, cash-intensive business=+15)</li>
     *   <li>Transaction patterns (velocity, structuring indicators)</li>
     *   <li>PEP status (+30)</li>
     *   <li>Adverse media hits (+20)</li>
     * </ul>
     *
     * @param customerId Customer to evaluate
     * @return Computed risk score (0-100)
     */
    public int evaluateCustomerRisk(Long customerId) {
        // Phase 1: Basic risk scoring framework.
        // Full rule-engine integration (configurable rules from aml_monitoring_rules table)
        // will be implemented in Phase 2.
        log.debug("AML risk evaluation requested for customer={}", customerId);
        return 0; // Default LOW risk — scoring logic to be wired with monitoring rules
    }
}
